---
- hosts: all
  sudo: yes
  tasks:

    - name: enable https apt functionality
      apt: name=apt-transport-https update_cache=yes

    - name: add nodesource key to apt
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

    - name: add nodesource repo to apt
      apt_repository: repo="{{ item }}"
      with_items:
        - deb https://deb.nodesource.com/node {{ ansible_lsb.codename }} main
        - deb-src https://deb.nodesource.com/node {{ ansible_lsb.codename }} main

    - name: install packages from apt
      apt: name={{ item }} 
      with_items:
        - python-pip
        - nodejs
        - git
        - vim
        - tmux
        - tree
        - ack-grep

    - name: install modules from pip
      pip: name={{ item }}
      with_items:
        - virtualenv
        - virtualenvwrapper
        - flake8
